# Generated by Django 5.2.7 on 2025-11-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='is_primary_admin',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='phone',
        ),
    ]
