# Generated by Django 5.2.7 on 2025-10-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
