# Generated by Django 5.2.7 on 2025-10-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='outstanding',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='rating',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
