# Generated by Django 5.2.7 on 2025-11-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0002_alter_purchaseorderitem_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='remarks',
            new_name='termscondition',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(choices=[('Immediate', 'Immediate'), ('30 Days', '30 Days'), ('60 Days', '60 Days')], default='Immediate', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
