# Generated by Django 5.2.7 on 2025-11-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ManyToManyField(related_name='clients', to='fabzen_app.company'),
        ),
    ]
