# Generated by Django 5.2.7 on 2025-10-16 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0003_party_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_street', models.CharField(max_length=100)),
                ('company_name_print', models.CharField(max_length=100)),
                ('address_line1', models.TextField()),
                ('address_line2', models.TextField()),
                ('address_line3', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('default_currency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=100, null=True)),
                ('micr_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='fabzen_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('fax_no', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='fabzen_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRegistraionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_no', models.CharField(blank=True, max_length=15, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=15, null=True)),
                ('tan_no', models.CharField(blank=True, max_length=15, null=True)),
                ('msme_no', models.CharField(blank=True, max_length=15, null=True)),
                ('udyan_no', models.CharField(blank=True, max_length=15, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register', to='fabzen_app.company')),
            ],
        ),
    ]
