# Generated by Django 5.2.7 on 2025-11-03 10:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0004_alter_purchaseorder_options_purchaseorderitem_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreyPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp_no', models.CharField(max_length=20, unique=True)),
                ('gp_date', models.DateField(default=datetime.date.today)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(choices=[('Immediate', 'Immediate'), ('30 Days', '30 Days'), ('60 Days', '60 Days')], default='Immediate', max_length=20)),
                ('total_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Partial', 'Partial'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Open', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grey Purchase',
                'verbose_name_plural': 'Grey Purchases',
                'ordering': ['-gp_date'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiveNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_no', models.CharField(max_length=20, unique=True)),
                ('grn_date', models.DateField(default=datetime.date.today)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('total_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabzen_app.purchaseorder')),
            ],
            options={
                'verbose_name': 'Goods Receive Note',
                'verbose_name_plural': 'Goods Receive Notes',
                'ordering': ['-grn_date'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiveNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('uom', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('garment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabzen_app.garment')),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fabzen_app.goodsreceivenote')),
            ],
        ),
        migrations.CreateModel(
            name='GreyPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('uom', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('garment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabzen_app.garment')),
                ('gp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fabzen_app.greypurchase')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_no', models.CharField(max_length=20, unique=True)),
                ('pr_date', models.DateField(default=datetime.date.today)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('total_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('grn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabzen_app.goodsreceivenote')),
            ],
            options={
                'verbose_name': 'Purchase Return',
                'verbose_name_plural': 'Purchase Returns',
                'ordering': ['-pr_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('uom', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('garment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabzen_app.garment')),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fabzen_app.purchasereturn')),
            ],
        ),
    ]
