# Generated by Django 5.2.7 on 2025-11-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0005_greypurchase_goodsreceivenote_goodsreceivenoteitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Partial', 'Partial'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Close', 'Close')], default='Open', max_length=20),
        ),
    ]
