# Generated by Django 5.2.7 on 2025-10-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0006_remove_companyregistraiondetails_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('quality_name', models.CharField(max_length=100, verbose_name='Quality Name')),
                ('construction', models.CharField(max_length=50, verbose_name='Construction')),
                ('width', models.CharField(max_length=10, verbose_name='Width (inches)')),
                ('gsm', models.PositiveIntegerField(verbose_name='GSM')),
                ('category', models.CharField(choices=[('Synthetic', 'Synthetic'), ('Voile', 'Voile'), ('Poplin', 'Poplin'), ('Cambric', 'Cambric'), ('Knit', 'Knit')], max_length=50, verbose_name='Category')),
                ('rate_per_meter', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate per Meter (₹)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fabric',
                'verbose_name_plural': 'Fabrics',
                'ordering': ['code'],
            },
        ),
    ]
