# Generated by Django 5.2.7 on 2025-11-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0006_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsreceivenote',
            old_name='remarks',
            new_name='termscondition',
        ),
        migrations.AddField(
            model_name='goodsreceivenote',
            name='payment_terms',
            field=models.CharField(choices=[('Immediate', 'Immediate'), ('30 Days', '30 Days'), ('60 Days', '60 Days')], default='Immediate', max_length=20),
        ),
    ]
