# Generated by Django 5.2.7 on 2025-11-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0007_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
