# Generated by Django 5.2.7 on 2025-11-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0007_rename_remarks_goodsreceivenote_termscondition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivenoteitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
