# Generated by Django 5.2.7 on 2025-10-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0007_fabric'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
