# Generated by Django 5.2.7 on 2025-10-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0008_fabric_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_category', models.CharField(choices=[('shirts', 'Shirts/T-shirts'), ('pants', 'Pants/Trousers'), ('ladies', 'Ladies Wear'), ('kids', 'Kids Wear')], max_length=50, verbose_name='Size Category')),
                ('size_label', models.CharField(help_text='e.g., M (40)', max_length=50, verbose_name='Size Label')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='Display Order')),
                ('chest', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Chest (cm)')),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Waist (cm)')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Length (cm)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
                'ordering': ['display_order'],
            },
        ),
    ]
