# Generated by Django 5.2.7 on 2025-11-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0008_client_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, related_name='clients', to='fabzen_app.company'),
        ),
    ]
