# Generated by Django 5.2.7 on 2025-11-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0008_goodsreceivenoteitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivenoteitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
