# Generated by Django 5.2.7 on 2025-10-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0009_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment_code', models.CharField(editable=False, max_length=10, unique=True)),
                ('garment_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Shirts', 'Shirts'), ('Casual', 'Casual'), ('Pants', 'Pants'), ('Ethnic', 'Ethnic'), ('Ladies', 'Ladies')], max_length=20)),
                ('rate_per_piece', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_fabric_consumption', models.CharField(blank=True, max_length=20, null=True)),
                ('avg_production_time', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fabric',
            name='construction',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Construction'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='gsm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='GSM'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='rate_per_meter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rate per Meter (₹)'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='width',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Width (inches)'),
        ),
    ]
