# Generated by Django 5.2.7 on 2025-11-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0009_alter_client_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
