# Generated by Django 5.2.7 on 2025-11-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0009_goodsreceivenoteitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivenoteitem',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
