# Generated by Django 5.2.7 on 2025-11-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0010_company_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='clients', to='fabzen_app.company'),
        ),
    ]
