# Generated by Django 5.2.7 on 2025-11-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0010_goodsreceivenoteitem_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='default_currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
