# Generated by Django 5.2.7 on 2025-10-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0010_garment_alter_fabric_construction_alter_fabric_gsm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_code', models.CharField(max_length=20, unique=True)),
                ('process_name', models.CharField(max_length=100)),
                ('process_type', models.CharField(choices=[('Job Work', 'Job Work'), ('In-house', 'In-house')], max_length=20)),
                ('unit', models.CharField(choices=[('Meter', 'Meter'), ('Piece', 'Piece'), ('Kg', 'Kg')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_time', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='garment',
            name='garment_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
