# Generated by Django 5.2.7 on 2025-11-18 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0011_alter_client_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='fabzen_app.company'),
        ),
    ]
