# Generated by Django 5.2.7 on 2025-10-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0011_process_alter_garment_garment_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=20, unique=True)),
                ('machine_name', models.CharField(max_length=100)),
                ('machine_type', models.CharField(choices=[('Stitching', 'Stitching'), ('Cutting', 'Cutting'), ('Finishing', 'Finishing'), ('Ironing', 'Ironing')], max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity_per_day', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('assigned_operator', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
