# Generated by Django 5.2.7 on 2025-11-04 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0011_alter_company_default_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greypurchase',
            old_name='remarks',
            new_name='termscondition',
        ),
        migrations.AddField(
            model_name='greypurchase',
            name='grn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabzen_app.goodsreceivenote'),
        ),
        migrations.AddField(
            model_name='greypurchase',
            name='received_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='greypurchase',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Partial', 'Partial'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Close', 'Close')], default='Open', max_length=20),
        ),
    ]
