# Generated by Django 5.2.7 on 2025-11-18 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0012_party_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
