# Generated by Django 5.2.7 on 2025-10-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0012_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('Running', 'Running'), ('Idle', 'Idle')], default='Running', max_length=100),
        ),
    ]
