# Generated by Django 5.2.7 on 2025-11-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0012_rename_remarks_greypurchase_termscondition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greypurchaseitem',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
