# Generated by Django 5.2.7 on 2025-10-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0013_machine_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_code', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Stitching', 'Stitching'), ('Cutting', 'Cutting'), ('Ironing', 'Ironing'), ('Packing', 'Packing'), ('Quality Control', 'Quality Control')], max_length=50)),
                ('mobile_number', models.CharField(max_length=15)),
                ('skills', models.TextField(blank=True, null=True)),
                ('date_of_joining', models.DateField()),
                ('daily_wage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
