# Generated by Django 5.2.7 on 2025-11-18 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0013_party_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabric_company', to='fabzen_app.company'),
        ),
    ]
