# Generated by Django 5.2.7 on 2025-11-04 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0013_greypurchaseitem_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturn',
            name='grn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabzen_app.greypurchase'),
        ),
    ]
