# Generated by Django 5.2.7 on 2025-11-18 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0014_fabric_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
