# Generated by Django 5.2.7 on 2025-10-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0014_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='is_active',
        ),
        migrations.AddField(
            model_name='operator',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('leave', 'Leave')], default='active', max_length=50),
        ),
    ]
