# Generated by Django 5.2.7 on 2025-11-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0014_alter_purchasereturn_grn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasereturn',
            old_name='grn',
            new_name='greypurchase',
        ),
    ]
