# Generated by Django 5.2.7 on 2025-10-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0015_remove_operator_is_active_operator_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_code', models.CharField(max_length=20, unique=True)),
                ('ledger_name', models.CharField(max_length=100)),
                ('ledger_group', models.CharField(choices=[('Direct Income', 'Direct Income'), ('Indirect Income', 'Indirect Income'), ('Direct Expenses', 'Direct Expenses'), ('Indirect Expenses', 'Indirect Expenses'), ('Miscellaneous Expenses', 'Miscellaneous Expenses'), ('Bank Accounts', 'Bank Accounts'), ('Cash', 'Cash'), ('Duties & Taxes', 'Duties & Taxes')], max_length=50)),
                ('opening_balance', models.BigIntegerField(default=0)),
                ('balance_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
