# Generated by Django 5.2.7 on 2025-11-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0015_rename_grn_purchasereturn_greypurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='payment_terms',
            field=models.CharField(choices=[('Immediate', 'Immediate'), ('30 Days', '30 Days'), ('60 Days', '60 Days')], default='Immediate', max_length=20),
        ),
    ]
