# Generated by Django 5.2.7 on 2025-11-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0016_purchasereturn_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='termscondition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
