# Generated by Django 5.2.7 on 2025-11-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0017_purchasereturn_termscondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturnitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
