# Generated by Django 5.2.7 on 2025-11-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0018_purchasereturnitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseindent',
            name='termscondition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
