# Generated by Django 5.2.7 on 2025-11-10 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0019_purchaseindent_termscondition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseindent',
            name='termscondition',
        ),
    ]
