# Generated by Django 5.2.7 on 2025-11-18 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0019_machine_company_machine_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_company', to='fabzen_app.company'),
        ),
        migrations.AddField(
            model_name='operator',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
