# Generated by Django 5.2.7 on 2025-11-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0020_remove_purchaseindent_termscondition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseindentitem',
            name='required_date',
        ),
    ]
