# Generated by Django 5.2.7 on 2025-11-18 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0020_operator_company_operator_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_company', to='fabzen_app.company'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledgergroup',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_company', to='fabzen_app.company'),
        ),
        migrations.AddField(
            model_name='ledgergroup',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ledgergroup',
            unique_together={('name', 'company')},
        ),
    ]
