# Generated by Django 5.2.7 on 2025-11-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0021_remove_purchaseindentitem_required_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='converted_status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20),
        ),
    ]
