# Generated by Django 5.2.7 on 2025-11-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0022_purchaseorder_converted_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseindentitem',
            name='converted_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseindentitem',
            name='pending_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
