# Generated by Django 5.2.7 on 2025-11-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0023_purchaseindentitem_converted_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseindentitem',
            name='preclosed_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
