# Generated by Django 5.2.7 on 2025-11-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabzen_app', '0024_purchaseindentitem_preclosed_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseindentitem',
            old_name='preclosed_qty',
            new_name='preclose_qty',
        ),
    ]
